server:
  port: 8080
  servlet:
    context-path: /nacos_consumer

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848 # nacos注册中心地址
        cluster-name: shanghai # 服务消费者所在集群名称
service-url:
  nacos-provider-service: http://nacos-provider
#    ribbon:
#      NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#  ribbon 默认的负载均衡策略是轮询机制，如果希望根据集群名称进行负载，则需要指定NacosRule
